dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
script:
- npm run build
- npm run test
deploy:
 provider: npm
 email: $NPM_EMAIL
 api_key: $NPM_API_KEY
 skip_cleanup: true
 on:
   tags: true